# Generated by Django 5.0.6 on 2026-06-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuentacontable",
            name="naturaleza",
            field=models.CharField(
                choices=[("debito", "Débito"), ("credito", "Crédito")], max_length=7
            ),
        ),
    ]
