# Generated by Django 5.0.6 on 2026-06-05 01:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Suscripcion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("basico", "Básico"),
                            ("pro", "Pro"),
                            ("clinica", "Clínica"),
                        ],
                        default="basico",
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activa", "Activa"),
                            ("vencida", "Vencida"),
                            ("suspendida", "Suspendida por impago"),
                            ("cancelada", "Cancelada"),
                            ("prueba", "Período de prueba"),
                        ],
                        default="prueba",
                        max_length=20,
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True,
                        help_text="Null = sin vencimiento (anual prepago)",
                        null=True,
                    ),
                ),
                (
                    "dias_gracia",
                    models.PositiveSmallIntegerField(
                        default=5, help_text="Días extra tras vencer antes de bloquear"
                    ),
                ),
                ("max_medicos", models.PositiveSmallIntegerField(default=1)),
                (
                    "max_facturas_mes",
                    models.PositiveIntegerField(default=100, help_text="0 = ilimitado"),
                ),
                ("referencia_pago", models.CharField(blank=True, max_length=100)),
                ("metodo_pago", models.CharField(blank=True, max_length=50)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "consultorio",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suscripcion",
                        to="tenants.consultorio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suscripción",
                "verbose_name_plural": "Suscripciones",
            },
        ),
        migrations.CreateModel(
            name="HistorialPago",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                ("moneda", models.CharField(default="COP", max_length=3)),
                ("referencia", models.CharField(max_length=100)),
                ("metodo", models.CharField(blank=True, max_length=50)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("aprobado", "Aprobado"),
                            ("rechazado", "Rechazado"),
                            ("pendiente", "Pendiente"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("meses_pagados", models.PositiveSmallIntegerField(default=1)),
                ("respuesta_pasarela", models.JSONField(blank=True, default=dict)),
                (
                    "suscripcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="suscripciones.suscripcion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
                "ordering": ["-fecha"],
            },
        ),
    ]
