# Generated by Django 5.0.6 on 2026-06-05 01:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pacientes", "0001_initial"),
        ("tarifas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Especialidad",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "codigo_rips",
                    models.CharField(
                        blank=True,
                        help_text="Código grupo servicios RIPS",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Sala",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: Consultorio 1, Sala de procedimientos",
                        max_length=50,
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Medico",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "registro_medico",
                    models.CharField(
                        help_text="Número de registro médico", max_length=20
                    ),
                ),
                (
                    "duracion_cita_min",
                    models.PositiveIntegerField(
                        default=20, help_text="Minutos por cita por defecto"
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "especialidades",
                    models.ManyToManyField(blank=True, to="citas.especialidad"),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medico",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["usuario__last_name"],
            },
        ),
        migrations.CreateModel(
            name="Cita",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fecha_hora_inicio", models.DateTimeField()),
                ("fecha_hora_fin", models.DateTimeField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("programada", "Programada"),
                            ("confirmada", "Confirmada"),
                            ("en_curso", "En curso"),
                            ("atendida", "Atendida"),
                            ("cancelada", "Cancelada"),
                            ("no_asistio", "No asistió"),
                        ],
                        default="programada",
                        max_length=20,
                    ),
                ),
                ("motivo_consulta", models.TextField(blank=True)),
                ("observaciones", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "convenio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tarifas.convenioeps",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="citas_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="citas",
                        to="pacientes.paciente",
                    ),
                ),
                (
                    "especialidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="citas.especialidad",
                    ),
                ),
                (
                    "medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="citas",
                        to="citas.medico",
                    ),
                ),
                (
                    "sala",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="citas.sala",
                    ),
                ),
            ],
            options={
                "ordering": ["fecha_hora_inicio"],
                "indexes": [
                    models.Index(
                        fields=["medico", "fecha_hora_inicio"],
                        name="citas_cita_medico__3e496f_idx",
                    ),
                    models.Index(
                        fields=["paciente", "fecha_hora_inicio"],
                        name="citas_cita_pacient_a7cd81_idx",
                    ),
                ],
            },
        ),
    ]
