# Generated by Django 5.0.6 on 2026-06-05 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cita",
            name="medico",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="citas",
                to="citas.medico",
            ),
        ),
    ]
