# Generated by Django 5.0.6 on 2026-06-07 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0003_medico_identificacion_rips"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medico",
            name="registro_medico",
            field=models.CharField(
                help_text="Número de registro médico (RETHUS)", max_length=20
            ),
        ),
    ]
