# Generated by Django 5.0.6 on 2026-06-06 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0005_especialidad"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="especialidad_principal",
            field=models.ForeignKey(
                blank=True,
                help_text="Especialidad principal del profesional",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="medicos_principal",
                to="catalogos.especialidad",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="especialidades",
            field=models.ManyToManyField(
                blank=True,
                help_text="Especialidades adicionales",
                related_name="medicos",
                to="catalogos.especialidad",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="firma_imagen",
            field=models.ImageField(
                blank=True,
                help_text="Imagen de la firma del profesional (PNG/JPG)",
                null=True,
                upload_to="firmas/",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="numero_rethus",
            field=models.CharField(
                blank=True,
                help_text="Número de registro ReTHUS (Ley 1164/2007)",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="tarjeta_profesional",
            field=models.CharField(
                blank=True,
                help_text="Número de tarjeta profesional (Colegio Médico Colombiano)",
                max_length=20,
            ),
        ),
    ]
