# Generated by Django 5.0.6 on 2026-06-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CodigoCUPS",
            fields=[
                (
                    "codigo",
                    models.CharField(
                        help_text="Código CUPS",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        help_text="Descripción del servicio o procedimiento",
                        max_length=400,
                    ),
                ),
                (
                    "nombre_servicio",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del servicio / especialidad",
                        max_length=200,
                    ),
                ),
                (
                    "grupo_servicio",
                    models.CharField(
                        blank=True,
                        help_text="Grupo de servicio (Quirúrgicos, Consulta, etc.)",
                        max_length=120,
                    ),
                ),
                (
                    "cobertura",
                    models.CharField(
                        blank=True, help_text="PBS / NO PBS", max_length=20
                    ),
                ),
                (
                    "codigo_reps",
                    models.CharField(
                        blank=True,
                        help_text="Código de servicio REPS homologado",
                        max_length=20,
                    ),
                ),
                (
                    "grupo_rips",
                    models.CharField(
                        blank=True, help_text="GrupoServicios_RIPS", max_length=10
                    ),
                ),
            ],
            options={
                "verbose_name": "Código CUPS",
                "verbose_name_plural": "Códigos CUPS",
                "ordering": ["codigo"],
                "indexes": [
                    models.Index(
                        fields=["descripcion"], name="catalogos_c_descrip_2951a3_idx"
                    ),
                    models.Index(
                        fields=["grupo_servicio"], name="catalogos_c_grupo_s_ec739d_idx"
                    ),
                ],
            },
        ),
    ]
