# Generated by Django 5.0.6 on 2026-06-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodigoCIE10",
            fields=[
                (
                    "codigo",
                    models.CharField(
                        help_text="Código CIE-10 (ej. A000, J189)",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre / descripción específica", max_length=400
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, help_text="Categoría diagnóstica", max_length=300
                    ),
                ),
                (
                    "capitulo_codigo",
                    models.CharField(
                        blank=True,
                        help_text="Código de capítulo (ej. A00)",
                        max_length=10,
                    ),
                ),
                (
                    "capitulo_desc",
                    models.CharField(
                        blank=True, help_text="Descripción del capítulo", max_length=200
                    ),
                ),
                ("habilitado", models.BooleanField(default=True)),
                (
                    "sexo",
                    models.CharField(
                        choices=[("A", "Ambos"), ("M", "Masculino"), ("F", "Femenino")],
                        default="A",
                        help_text="Restricción de sexo: A Ambos, M Masculino, F Femenino",
                        max_length=1,
                    ),
                ),
                ("edad_minima", models.PositiveSmallIntegerField(default=0)),
                ("edad_maxima", models.PositiveSmallIntegerField(default=999)),
            ],
            options={
                "verbose_name": "Código CIE-10",
                "verbose_name_plural": "Códigos CIE-10",
                "ordering": ["codigo"],
                "indexes": [
                    models.Index(
                        fields=["nombre"], name="catalogos_c_nombre_fb07a8_idx"
                    ),
                    models.Index(
                        fields=["capitulo_codigo"],
                        name="catalogos_c_capitul_c0b918_idx",
                    ),
                ],
            },
        ),
    ]
