# Generated by Django 5.0.6 on 2026-06-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0004_catalogomedicamento"),
    ]

    operations = [
        migrations.CreateModel(
            name="Especialidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Código ReTHUS", max_length=10, unique=True
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Especialidad",
                "verbose_name_plural": "Especialidades",
                "ordering": ["nombre"],
            },
        ),
        migrations.RenameIndex(
            model_name="catalogomedicamento",
            new_name="catalogos_c_princip_5f3113_idx",
            old_name="catalogos_p_princip_idx",
        ),
        migrations.RenameIndex(
            model_name="catalogomedicamento",
            new_name="catalogos_c_vigente_cffe24_idx",
            old_name="catalogos_m_vigente_idx",
        ),
    ]
