# Generated by Django 5.0.6 on 2026-07-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0005_especialidad"),
    ]

    operations = [
        migrations.AddField(
            model_name="codigocups",
            name="grupo_soat",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Grupo quirúrgico SOAT (2-13, 20-23) del procedimiento",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="codigocups",
            name="uvr",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Puntos UVR ISS 2001 del procedimiento (liquidación de cirugías)",
                max_digits=10,
                null=True,
            ),
        ),
    ]
