# Generated by Django 5.0.6 on 2026-06-05 01:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aseguradora",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("nit", models.CharField(max_length=20, unique=True)),
                (
                    "codigo",
                    models.CharField(help_text="Código RIPS MinSalud", max_length=10),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("EPS", "EPS"),
                            ("PREPAGADA", "Medicina prepagada"),
                            ("ARL", "ARL"),
                            ("SOAT", "SOAT"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo_identificacion",
                    models.CharField(
                        choices=[
                            ("CC", "Cédula de ciudadanía"),
                            ("CE", "Cédula de extranjería"),
                            ("TI", "Tarjeta de identidad"),
                            ("RC", "Registro civil"),
                            ("PA", "Pasaporte"),
                            ("MS", "Menor sin identificación"),
                            ("AS", "Adulto sin identificación"),
                            ("NIT", "NIT"),
                        ],
                        max_length=5,
                    ),
                ),
                ("numero_identificacion", models.CharField(max_length=30)),
                ("primer_nombre", models.CharField(max_length=80)),
                ("segundo_nombre", models.CharField(blank=True, max_length=80)),
                ("primer_apellido", models.CharField(max_length=80)),
                ("segundo_apellido", models.CharField(blank=True, max_length=80)),
                ("fecha_nacimiento", models.DateField()),
                (
                    "sexo",
                    models.CharField(
                        choices=[
                            ("M", "Masculino"),
                            ("F", "Femenino"),
                            ("I", "Indeterminado"),
                        ],
                        max_length=1,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("direccion", models.CharField(blank=True, max_length=200)),
                (
                    "municipio_codigo",
                    models.CharField(
                        blank=True, help_text="Código DANE", max_length=10
                    ),
                ),
                (
                    "regimen",
                    models.CharField(
                        choices=[
                            ("C", "Contributivo"),
                            ("S", "Subsidiado"),
                            ("V", "Vinculado"),
                            ("P", "Particular"),
                            ("A", "ARP / ARL"),
                            ("T", "SOAT"),
                            ("O", "Otro"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("numero_poliza", models.CharField(blank=True, max_length=50)),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "aseguradora",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pacientes",
                        to="pacientes.aseguradora",
                    ),
                ),
            ],
            options={
                "ordering": ["primer_apellido", "primer_nombre"],
                "unique_together": {("tipo_identificacion", "numero_identificacion")},
            },
        ),
    ]
