# Generated by Django 5.0.6 on 2026-06-05 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0001_initial"),
        ("tarifas", "0002_manualtarifario_itemtarifario"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="tarifa",
            field=models.ForeignKey(
                blank=True,
                help_text="Tarifa asignada a este paciente. Si está vacío, se usa la predeterminada del consultorio.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pacientes",
                to="tarifas.manualtarifario",
            ),
        ),
    ]
