# Generated by Django 5.0.6 on 2026-06-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0003_aseguradora_tarifario"),
    ]

    operations = [
        migrations.AddField(
            model_name="aseguradora",
            name="porcentaje_ajuste",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="% contractual adicional sobre el tarifario. Ej: 35 = +35%",
                max_digits=6,
            ),
        ),
    ]
