# Generated by Django 5.0.6 on 2026-06-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0004_add_porcentaje_aseguradora_y_paquetes_tarifario"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aseguradora",
            options={"ordering": ["nombre", "regimen"]},
        ),
        migrations.AddField(
            model_name="aseguradora",
            name="regimen",
            field=models.CharField(
                blank=True,
                choices=[
                    ("C", "Contributivo"),
                    ("S", "Subsidiado"),
                    ("V", "Vinculado"),
                    ("P", "Particular"),
                    ("A", "ARP / ARL"),
                    ("T", "SOAT"),
                    ("O", "Otro"),
                ],
                help_text="Régimen de afiliación (C=Contributivo, S=Subsidiado, …). Permite que una misma EPS tenga dos entradas con distinto régimen.",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="aseguradora",
            name="nit",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name="aseguradora",
            unique_together={("nit", "regimen")},
        ),
    ]
