# Generated by Django 5.0.6 on 2026-06-06 15:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("historia", "0004_numero_hc_ordenhc"),
        ("pacientes", "0003_aseguradora_tarifario"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordenhc",
            name="indicacion",
            field=models.TextField(
                blank=True, help_text="Indicación clínica / justificación"
            ),
        ),
        migrations.CreateModel(
            name="AyudaDiagnostica",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("laboratorio", "Laboratorio clínico"),
                            ("rx", "Radiografía"),
                            ("ecografia", "Ecografía"),
                            ("tomografia", "Tomografía (TAC)"),
                            ("resonancia", "Resonancia magnética (RMN)"),
                            ("electrocardiograma", "Electrocardiograma"),
                            ("ecocardiograma", "Ecocardiograma"),
                            ("endoscopia", "Endoscopia"),
                            ("biopsia", "Biopsia / Patología"),
                            ("espirometria", "Espirometría"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cups", models.CharField(blank=True, max_length=10)),
                ("descripcion", models.CharField(max_length=300)),
                ("indicacion_clinica", models.TextField(blank=True)),
                ("urgente", models.BooleanField(default=False)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("solicitada", "Solicitada"),
                            ("tomada", "Tomada/Procesada"),
                            ("resultado", "Con resultado"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="solicitada",
                        max_length=15,
                    ),
                ),
                ("fecha_solicitud", models.DateTimeField(auto_now_add=True)),
                (
                    "historia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ayudas_diagnosticas",
                        to="historia.historiaclinica",
                    ),
                ),
                (
                    "ingreso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ayudas_diagnosticas",
                        to="historia.ingreso",
                    ),
                ),
                (
                    "medico_solicitante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ayudas_solicitadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ayuda diagnóstica",
                "verbose_name_plural": "Ayudas diagnósticas",
                "ordering": ["-fecha_solicitud"],
            },
        ),
        migrations.CreateModel(
            name="NotaMedica",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ingreso", "Nota de ingreso/admisión"),
                            ("evolucion", "Evolución médica"),
                            ("interconsulta", "Interconsulta"),
                            ("valoracion", "Valoración por especialidad"),
                            ("preoperatoria", "Valoración preoperatoria"),
                            ("postoperatoria", "Nota postoperatoria"),
                            ("anestesia", "Valoración anestésica"),
                            ("enfermeria", "Nota de enfermería"),
                            ("aclaratoria", "Nota aclaratoria"),
                            ("epicrisis", "Epicrisis / Resumen de egreso"),
                        ],
                        default="evolucion",
                        max_length=20,
                    ),
                ),
                ("especialidad_nota", models.CharField(blank=True, max_length=200)),
                ("tarjeta_prof_nota", models.CharField(blank=True, max_length=20)),
                (
                    "servicio",
                    models.CharField(
                        blank=True,
                        help_text="Servicio/sala hospitalaria (ej: Medicina Interna, UCI)",
                        max_length=100,
                    ),
                ),
                (
                    "fecha_hora",
                    models.DateTimeField(help_text="Fecha y hora de la evolución"),
                ),
                (
                    "subjetivo",
                    models.TextField(
                        blank=True,
                        help_text="Síntomas y quejas referidas por el paciente",
                    ),
                ),
                (
                    "objetivo",
                    models.TextField(
                        blank=True,
                        help_text="Examen físico, signos vitales, paraclínicos",
                    ),
                ),
                (
                    "analisis",
                    models.TextField(
                        blank=True, help_text="Análisis / impresión diagnóstica"
                    ),
                ),
                (
                    "plan",
                    models.TextField(
                        blank=True, help_text="Plan de manejo, órdenes, conducta"
                    ),
                ),
                ("resumen_hospitalizacion", models.TextField(blank=True)),
                (
                    "diagnostico_egreso",
                    models.CharField(blank=True, help_text="CIE-10", max_length=10),
                ),
                (
                    "desc_diagnostico_egreso",
                    models.CharField(blank=True, max_length=300),
                ),
                ("condicion_al_egreso", models.TextField(blank=True)),
                ("recomendaciones_egreso", models.TextField(blank=True)),
                ("firmada", models.BooleanField(default=False)),
                ("firmada_en", models.DateTimeField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "historia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notas_medicas",
                        to="historia.historiaclinica",
                    ),
                ),
                (
                    "ingreso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas_medicas",
                        to="historia.ingreso",
                    ),
                ),
                (
                    "medico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notas_medicas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota médica",
                "verbose_name_plural": "Notas médicas",
                "ordering": ["fecha_hora"],
            },
        ),
        migrations.CreateModel(
            name="ProgramacionCx",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "numero_cx",
                    models.PositiveIntegerField(
                        editable=False, help_text="Consecutivo CX-XXXXX"
                    ),
                ),
                (
                    "cups_principal",
                    models.CharField(
                        help_text="CUPS del procedimiento principal", max_length=10
                    ),
                ),
                ("descripcion_cups", models.CharField(blank=True, max_length=300)),
                (
                    "diagnostico_preop",
                    models.CharField(
                        blank=True, help_text="CIE-10 preoperatorio", max_length=10
                    ),
                ),
                (
                    "desc_diagnostico_preop",
                    models.CharField(blank=True, max_length=300),
                ),
                (
                    "tipo_cirugia",
                    models.CharField(
                        choices=[
                            ("electiva", "Electiva"),
                            ("urgente", "Urgente"),
                            ("emergencia", "Emergencia"),
                        ],
                        default="electiva",
                        max_length=15,
                    ),
                ),
                ("fecha_programada", models.DateTimeField()),
                ("duracion_estimada_min", models.PositiveIntegerField(default=60)),
                ("quirofano", models.CharField(blank=True, max_length=50)),
                (
                    "tipo_anestesia",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("regional", "Regional"),
                            ("local", "Local"),
                            ("sedacion", "Sedación"),
                            ("epidural", "Epidural"),
                            ("raquidea", "Raquídea"),
                            ("mixta", "Mixta"),
                        ],
                        default="general",
                        max_length=10,
                    ),
                ),
                ("numero_autorizacion", models.CharField(blank=True, max_length=60)),
                ("requiere_autorizacion", models.BooleanField(default=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("programada", "Programada"),
                            ("confirmada", "Confirmada"),
                            ("en_curso", "En curso"),
                            ("realizada", "Realizada"),
                            ("suspendida", "Suspendida"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="programada",
                        max_length=15,
                    ),
                ),
                ("observaciones_preop", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "anestesiologo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cx_como_anestesiologo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cirujano",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cx_como_cirujano",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ingreso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="programaciones_cx",
                        to="historia.ingreso",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programaciones_cx",
                        to="pacientes.paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programación quirúrgica",
                "verbose_name_plural": "Programaciones quirúrgicas",
                "ordering": ["-fecha_programada"],
            },
        ),
        migrations.CreateModel(
            name="DescripcionQuirurgica",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("numero_dqx", models.PositiveIntegerField(editable=False)),
                (
                    "diagnostico_preoperatorio",
                    models.CharField(blank=True, help_text="CIE-10", max_length=10),
                ),
                ("desc_diag_preop", models.CharField(blank=True, max_length=300)),
                (
                    "diagnostico_postoperatorio",
                    models.CharField(blank=True, help_text="CIE-10", max_length=10),
                ),
                ("desc_diag_postop", models.CharField(blank=True, max_length=300)),
                ("cups_principal", models.CharField(max_length=10)),
                (
                    "descripcion_procedimiento",
                    models.CharField(blank=True, max_length=300),
                ),
                (
                    "tipo_anestesia",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("regional", "Regional"),
                            ("local", "Local"),
                            ("sedacion", "Sedación"),
                            ("epidural", "Epidural"),
                            ("raquidea", "Raquídea"),
                            ("mixta", "Mixta"),
                        ],
                        default="general",
                        max_length=10,
                    ),
                ),
                ("cirujano_nombre", models.CharField(blank=True, max_length=200)),
                (
                    "cirujano_tp",
                    models.CharField(
                        blank=True,
                        help_text="TP del cirujano al momento de la firma",
                        max_length=20,
                    ),
                ),
                ("cirujano_especialidad", models.CharField(blank=True, max_length=200)),
                ("anestesiologo_nombre", models.CharField(blank=True, max_length=200)),
                ("primer_ayudante", models.CharField(blank=True, max_length=200)),
                ("segundo_ayudante", models.CharField(blank=True, max_length=200)),
                ("instrumentadora", models.CharField(blank=True, max_length=200)),
                ("enfermera_circulante", models.CharField(blank=True, max_length=200)),
                ("fecha_hora_inicio", models.DateTimeField()),
                ("fecha_hora_fin", models.DateTimeField(blank=True, null=True)),
                ("quirofano", models.CharField(blank=True, max_length=50)),
                (
                    "descripcion_tecnica",
                    models.TextField(
                        help_text="Descripción paso a paso de la técnica quirúrgica utilizada"
                    ),
                ),
                (
                    "hallazgos",
                    models.TextField(
                        blank=True, help_text="Hallazgos intraoperatorios relevantes"
                    ),
                ),
                (
                    "especimenes",
                    models.TextField(
                        blank=True, help_text="Especímenes enviados a patología"
                    ),
                ),
                (
                    "implantes",
                    models.TextField(
                        blank=True,
                        help_text="Implantes, prótesis, mallas o dispositivos utilizados",
                    ),
                ),
                ("complicaciones", models.TextField(blank=True)),
                (
                    "sangrado_estimado_ml",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("liquidos_administrados", models.TextField(blank=True)),
                ("plan_postoperatorio", models.TextField(blank=True)),
                ("firmada", models.BooleanField(default=False)),
                ("firmada_en", models.DateTimeField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "anestesiologo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dqx_anestesiologo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cirujano",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dqx_cirujano",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ingreso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="descripciones_qx",
                        to="historia.ingreso",
                    ),
                ),
                (
                    "programacion",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="descripcion_qx",
                        to="historia.programacioncx",
                    ),
                ),
            ],
            options={
                "verbose_name": "Descripción quirúrgica",
                "verbose_name_plural": "Descripciones quirúrgicas",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="ResultadoAD",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fecha_resultado", models.DateTimeField()),
                (
                    "resultado_texto",
                    models.TextField(
                        blank=True, help_text="Texto del resultado / informe"
                    ),
                ),
                (
                    "interpretacion",
                    models.TextField(blank=True, help_text="Interpretación clínica"),
                ),
                ("conclusion", models.TextField(blank=True)),
                (
                    "archivo",
                    models.FileField(
                        blank=True,
                        help_text="PDF, imagen, DICOM thumbnail",
                        null=True,
                        upload_to="ayudas_diagnosticas/%Y/%m/",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "ayuda",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultado",
                        to="historia.ayudadiagnostica",
                    ),
                ),
                (
                    "medico_interpreta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resultados_interpretados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado ayuda diagnóstica",
                "verbose_name_plural": "Resultados ayudas diagnósticas",
            },
        ),
        migrations.AddIndex(
            model_name="programacioncx",
            index=models.Index(
                fields=["numero_cx"], name="historia_pr_numero__9ebda4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="programacioncx",
            index=models.Index(
                fields=["paciente", "estado"], name="historia_pr_pacient_cce8a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="descripcionquirurgica",
            index=models.Index(
                fields=["numero_dqx"], name="historia_de_numero__78d88e_idx"
            ),
        ),
    ]
