from django.db import migrations, models
import django.db.models.deletion
import uuid
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0005_salud_notas_cx_ayudas'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ── Triage ────────────────────────────────────────────────────────────
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('nivel', models.PositiveSmallIntegerField(choices=[(1,'Nivel I — Reanimación (rojo)'),(2,'Nivel II — Emergencia (naranja)'),(3,'Nivel III — Urgencia (amarillo)'),(4,'Nivel IV — Menos urgente (verde)'),(5,'Nivel V — Sin urgencia (azul)')])),
                ('motivo_consulta', models.TextField()),
                ('hora_clasificacion', models.DateTimeField(auto_now_add=True)),
                ('tension_arterial', models.CharField(blank=True, max_length=15)),
                ('frecuencia_cardiaca', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('frecuencia_resp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('spo2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('glasgow', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dolor_escala', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('mecanismo_trauma', models.CharField(blank=True, max_length=200)),
                ('alergias', models.TextField(blank=True)),
                ('medicamentos_actuales', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('espera','En espera'),('en_atencion','En atención'),('atendido','Atendido'),('referido','Referido'),('abandono','Abandono')], default='espera', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('hora_atencion', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='triages', to='pacientes.paciente')),
                ('ingreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triages', to='historia.ingreso')),
                ('clasificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triages_clasificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['hora_clasificacion'], 'verbose_name': 'Triage', 'verbose_name_plural': 'Triages'},
        ),
        migrations.AddIndex(model_name='triage', index=models.Index(fields=['nivel', 'estado'], name='historia_triage_nivel_estado_idx')),
        migrations.AddIndex(model_name='triage', index=models.Index(fields=['hora_clasificacion'], name='historia_triage_hora_idx')),

        # ── ListaVerificacionQx ───────────────────────────────────────────────
        migrations.CreateModel(
            name='ListaVerificacionQx',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('entrada_identidad', models.BooleanField(default=False)),
                ('entrada_sitio_marcado', models.BooleanField(default=False)),
                ('entrada_anestesia_revisada', models.BooleanField(default=False)),
                ('entrada_oximetro', models.BooleanField(default=False)),
                ('entrada_alergias', models.BooleanField(default=False)),
                ('entrada_via_aerea', models.BooleanField(default=False)),
                ('entrada_sangrado', models.BooleanField(default=False)),
                ('entrada_consentimiento', models.BooleanField(default=False)),
                ('entrada_ayuno', models.BooleanField(default=False)),
                ('entrada_notas_entrada', models.TextField(blank=True)),
                ('entrada_hora', models.DateTimeField(blank=True, null=True)),
                ('acto_presentacion_equipo', models.BooleanField(default=False)),
                ('acto_confirmacion_paciente', models.BooleanField(default=False)),
                ('acto_profilaxis_antibiotica', models.BooleanField(default=False)),
                ('acto_estudios_imagen', models.BooleanField(default=False)),
                ('acto_implantes', models.BooleanField(default=False)),
                ('acto_pasos_criticos', models.TextField(blank=True)),
                ('acto_preocupaciones_anest', models.TextField(blank=True)),
                ('acto_preocupaciones_enf', models.TextField(blank=True)),
                ('acto_hora', models.DateTimeField(blank=True, null=True)),
                ('salida_nombre_procedimiento', models.BooleanField(default=False)),
                ('salida_conteo_instrumentos', models.BooleanField(default=False)),
                ('salida_especimenes', models.BooleanField(default=False)),
                ('salida_equipos_problemas', models.BooleanField(default=False)),
                ('salida_recuperacion', models.TextField(blank=True)),
                ('salida_hora', models.DateTimeField(blank=True, null=True)),
                ('completada', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('programacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lista_verificacion', to='historia.programacioncx')),
                ('entrada_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_qx', to=settings.AUTH_USER_MODEL)),
                ('acto_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actos_qx', to=settings.AUTH_USER_MODEL)),
                ('salida_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_qx', to=settings.AUTH_USER_MODEL)),
            ],
            options={'verbose_name': 'Lista de verificación quirúrgica', 'verbose_name_plural': 'Listas de verificación quirúrgica'},
        ),

        # ── RegistroAnestesia ─────────────────────────────────────────────────
        migrations.CreateModel(
            name='RegistroAnestesia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('tipo_anestesia', models.CharField(choices=[('general','General'),('regional','Regional'),('local','Local'),('sedacion','Sedación'),('mixta','Mixta'),('espinal','Espinal/Raquídea'),('epidural','Epidural'),('peridural','Peridural')], default='general', max_length=15)),
                ('clasificacion_asa', models.CharField(choices=[('1','ASA 1'),('2','ASA 2'),('3','ASA 3'),('4','ASA 4'),('5','ASA 5'),('6','ASA 6')], default='1', max_length=2)),
                ('hora_inicio_anestesia', models.DateTimeField(blank=True, null=True)),
                ('hora_inicio_cirugia', models.DateTimeField(blank=True, null=True)),
                ('hora_fin_cirugia', models.DateTimeField(blank=True, null=True)),
                ('hora_fin_anestesia', models.DateTimeField(blank=True, null=True)),
                ('induccion', models.JSONField(blank=True, default=list)),
                ('mantenimiento', models.JSONField(blank=True, default=list)),
                ('reversión', models.JSONField(blank=True, default=list)),
                ('fluidos', models.JSONField(blank=True, default=list)),
                ('signos_vitales_intra', models.JSONField(blank=True, default=list)),
                ('sangrado_ml', models.PositiveIntegerField(blank=True, null=True)),
                ('diuresis_ml', models.PositiveIntegerField(blank=True, null=True)),
                ('transfusiones', models.TextField(blank=True)),
                ('complicaciones', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('condicion_egreso_qx', models.CharField(blank=True, max_length=200)),
                ('firmado', models.BooleanField(default=False)),
                ('firmado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('programacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registro_anestesia', to='historia.programacioncx')),
                ('anestesiologo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_anestesia', to=settings.AUTH_USER_MODEL)),
            ],
            options={'verbose_name': 'Registro de anestesia', 'verbose_name_plural': 'Registros de anestesia'},
        ),

        # ── ConsentimientoInformado ───────────────────────────────────────────
        migrations.CreateModel(
            name='ConsentimientoInformado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('tipo', models.CharField(choices=[('general','Consentimiento general de hospitalización'),('cirugia','Consentimiento quirúrgico'),('anestesia','Consentimiento anestésico'),('procedimiento','Procedimiento invasivo/diagnóstico'),('transfusion','Transfusión de hemoderivados'),('quimioterapia','Quimioterapia'),('investigacion','Participación en investigación'),('imagen','Uso de imágenes/datos clínicos'),('telemedicina','Teleconsulta/Telemedicina'),('otro','Otro')], max_length=20)),
                ('procedimiento', models.CharField(blank=True, max_length=300)),
                ('cups_procedimiento', models.CharField(blank=True, max_length=10)),
                ('texto_completo', models.TextField()),
                ('riesgos_informados', models.TextField(blank=True)),
                ('alternativas_informadas', models.TextField(blank=True)),
                ('nombre_paciente_firmante', models.CharField(blank=True, max_length=200)),
                ('nombre_acompanante', models.CharField(blank=True, max_length=200)),
                ('parentesco_acompanante', models.CharField(blank=True, max_length=100)),
                ('motivo_representante', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('pendiente','Pendiente de firma'),('firmado','Firmado'),('rechazado','Rechazado por paciente'),('anulado','Anulado')], default='pendiente', max_length=15)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('fecha_firma', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consentimientos', to='pacientes.paciente')),
                ('ingreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos', to='historia.ingreso')),
                ('programacion_cx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos', to='historia.programacioncx')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos_firmados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-creado_en'], 'verbose_name': 'Consentimiento informado', 'verbose_name_plural': 'Consentimientos informados'},
        ),

        # ── NotaEnfermeria ────────────────────────────────────────────────────
        migrations.CreateModel(
            name='NotaEnfermeria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('turno', models.CharField(choices=[('manana','Mañana (6am-2pm)'),('tarde','Tarde (2pm-10pm)'),('noche','Noche (10pm-6am)')], max_length=10)),
                ('fecha_hora', models.DateTimeField()),
                ('tension_arterial', models.CharField(blank=True, max_length=15)),
                ('frecuencia_cardiaca', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('frecuencia_resp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('spo2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('glasgow', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dolor_escala', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('entradas_ml', models.JSONField(blank=True, default=list)),
                ('salidas_ml', models.JSONField(blank=True, default=list)),
                ('balance_hidrico', models.IntegerField(blank=True, null=True)),
                ('medicamentos_administrados', models.JSONField(blank=True, default=list)),
                ('curaciones', models.TextField(blank=True)),
                ('sondas_catéteres', models.TextField(blank=True)),
                ('movilizacion', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('firmada', models.BooleanField(default=False)),
                ('firmada_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_enfermeria', to='historia.ingreso')),
                ('enfermero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_enfermeria', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'Nota de enfermería', 'verbose_name_plural': 'Notas de enfermería'},
        ),
    ]
