# Generated by Django 5.0.6 on 2026-06-07 00:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("historia", "0007_referencias_rehab_odonto_tele_uci_sangre"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="triage",
            new_name="historia_tr_nivel_485332_idx",
            old_name="historia_triage_nivel_estado_idx",
        ),
        migrations.RenameIndex(
            model_name="triage",
            new_name="historia_tr_hora_cl_2f02c8_idx",
            old_name="historia_triage_hora_idx",
        ),
        migrations.AlterField(
            model_name="consentimientoinformado",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="consentimientoinformado",
            name="motivo_representante",
            field=models.CharField(
                blank=True,
                help_text="Por qué firma el representante en vez del paciente",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="consentimientoinformado",
            name="nombre_acompanante",
            field=models.CharField(
                blank=True,
                help_text="Si firma representante legal/familiar",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="consentimientoinformado",
            name="procedimiento",
            field=models.CharField(
                blank=True,
                help_text="Nombre del procedimiento o intervención",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="consentimientoinformado",
            name="texto_completo",
            field=models.TextField(
                help_text="Texto completo del consentimiento informado"
            ),
        ),
        migrations.AlterField(
            model_name="listaverificacionqx",
            name="acto_confirmacion_paciente",
            field=models.BooleanField(
                default=False, help_text="Identidad, sitio y procedimiento confirmados"
            ),
        ),
        migrations.AlterField(
            model_name="listaverificacionqx",
            name="acto_estudios_imagen",
            field=models.BooleanField(
                default=False, help_text="Imágenes diagnósticas necesarias visibles"
            ),
        ),
        migrations.AlterField(
            model_name="listaverificacionqx",
            name="acto_implantes",
            field=models.BooleanField(
                default=False, help_text="Implantes/equipos especiales disponibles"
            ),
        ),
        migrations.AlterField(
            model_name="listaverificacionqx",
            name="acto_pasos_criticos",
            field=models.TextField(
                blank=True,
                help_text="Pasos críticos o inesperados anticipados por cirujano",
            ),
        ),
        migrations.AlterField(
            model_name="listaverificacionqx",
            name="acto_preocupaciones_anest",
            field=models.TextField(
                blank=True, help_text="Preocupaciones específicas del anestesiólogo"
            ),
        ),
        migrations.AlterField(
            model_name="listaverificacionqx",
            name="acto_preocupaciones_enf",
            field=models.TextField(
                blank=True, help_text="Preocupaciones del equipo de enfermería"
            ),
        ),
        migrations.AlterField(
            model_name="listaverificacionqx",
            name="acto_presentacion_equipo",
            field=models.BooleanField(
                default=False,
                help_text="Todos los miembros se presentaron por nombre y función",
            ),
        ),
        migrations.AlterField(
            model_name="listaverificacionqx",
            name="acto_profilaxis_antibiotica",
            field=models.BooleanField(
                default=False,
                help_text="Profilaxis antibiótica administrada en últimos 60 min",
            ),
        ),
        migrations.AlterField(
            model_name="listaverificacionqx",
            name="entrada_alergias",
            field=models.BooleanField(
                default=False, help_text="Alergias conocidas verificadas"
            ),
        ),
        migrations.AlterField(
            model_name="listaverificacionqx",
            name="entrada_anestesia_revisada",
            field=models.BooleanField(
                default=False, help_text="Revisión de seguridad anestésica completa"
            ),
        ),
        migrations.AlterField(
            model_name="listaverificacionqx",
            name="entrada_ayuno",
            field=models.BooleanField(default=False, help_text="Ayuno verificado"),
        ),
        migrations.AlterField(
            model_name="listaverificacionqx",
            name="entrada_consentimiento",
            field=models.BooleanField(
                default=False, help_text="Consentimiento informado firmado"
            ),
        ),
        migrations.AlterField(
            model_name="listaverificacionqx",
            name="entrada_identidad",
            field=models.BooleanField(
                default=False,
                help_text="Paciente confirmó identidad, procedimiento y sitio",
            ),
        ),
        migrations.AlterField(
            model_name="listaverificacionqx",
            name="entrada_oximetro",
            field=models.BooleanField(
                default=False, help_text="Oxímetro de pulso funcionando"
            ),
        ),
        migrations.AlterField(
            model_name="listaverificacionqx",
            name="entrada_sangrado",
            field=models.BooleanField(
                default=False, help_text="Riesgo de pérdida sanguínea > 500 ml evaluado"
            ),
        ),
        migrations.AlterField(
            model_name="listaverificacionqx",
            name="entrada_sitio_marcado",
            field=models.BooleanField(
                default=False, help_text="Sitio quirúrgico marcado"
            ),
        ),
        migrations.AlterField(
            model_name="listaverificacionqx",
            name="entrada_via_aerea",
            field=models.BooleanField(
                default=False, help_text="Vía aérea/riesgo de aspiración evaluado"
            ),
        ),
        migrations.AlterField(
            model_name="listaverificacionqx",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="listaverificacionqx",
            name="salida_conteo_instrumentos",
            field=models.BooleanField(
                default=False, help_text="Conteo de compresas e instrumentos completo"
            ),
        ),
        migrations.AlterField(
            model_name="listaverificacionqx",
            name="salida_equipos_problemas",
            field=models.BooleanField(
                default=False, help_text="Problemas con equipos registrados"
            ),
        ),
        migrations.AlterField(
            model_name="listaverificacionqx",
            name="salida_especimenes",
            field=models.BooleanField(
                default=False, help_text="Especímenes etiquetados correctamente"
            ),
        ),
        migrations.AlterField(
            model_name="listaverificacionqx",
            name="salida_nombre_procedimiento",
            field=models.BooleanField(
                default=False, help_text="Nombre del procedimiento registrado"
            ),
        ),
        migrations.AlterField(
            model_name="listaverificacionqx",
            name="salida_recuperacion",
            field=models.TextField(
                blank=True,
                help_text="Instrucciones de recuperación y manejo postoperatorio",
            ),
        ),
        migrations.AlterField(
            model_name="notaenfermeria",
            name="balance_hidrico",
            field=models.IntegerField(
                blank=True, help_text="Total entradas - salidas en ml", null=True
            ),
        ),
        migrations.AlterField(
            model_name="notaenfermeria",
            name="curaciones",
            field=models.TextField(
                blank=True, help_text="Curaciones realizadas, estado de heridas"
            ),
        ),
        migrations.AlterField(
            model_name="notaenfermeria",
            name="entradas_ml",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="[{tipo, volumen_ml}] líquidos administrados",
            ),
        ),
        migrations.AlterField(
            model_name="notaenfermeria",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="notaenfermeria",
            name="medicamentos_administrados",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="[{medicamento, dosis, via, hora, enfermero}]",
            ),
        ),
        migrations.AlterField(
            model_name="notaenfermeria",
            name="movilizacion",
            field=models.TextField(
                blank=True, help_text="Cambios de posición, movilización"
            ),
        ),
        migrations.AlterField(
            model_name="notaenfermeria",
            name="salidas_ml",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="[{tipo, volumen_ml}] diuresis, drenajes, etc.",
            ),
        ),
        migrations.AlterField(
            model_name="notaenfermeria",
            name="sondas_catéteres",
            field=models.TextField(
                blank=True, help_text="Estado de sondas, catéteres, drenajes"
            ),
        ),
        migrations.AlterField(
            model_name="registroanestesia",
            name="clasificacion_asa",
            field=models.CharField(
                choices=[
                    ("1", "ASA 1"),
                    ("2", "ASA 2"),
                    ("3", "ASA 3"),
                    ("4", "ASA 4"),
                    ("5", "ASA 5"),
                    ("6", "ASA 6"),
                ],
                default="1",
                help_text="Clasificación ASA del paciente",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="registroanestesia",
            name="condicion_egreso_qx",
            field=models.CharField(
                blank=True, help_text="Condición al salir del quirófano", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="registroanestesia",
            name="fluidos",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="[{tipo, volumen_ml}] SSN, Lactato Ringer, etc.",
            ),
        ),
        migrations.AlterField(
            model_name="registroanestesia",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="registroanestesia",
            name="induccion",
            field=models.JSONField(
                blank=True, default=list, help_text="[{medicamento, dosis, via}]"
            ),
        ),
        migrations.AlterField(
            model_name="registroanestesia",
            name="mantenimiento",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="[{medicamento, dosis, concentracion}]",
            ),
        ),
        migrations.AlterField(
            model_name="registroanestesia",
            name="signos_vitales_intra",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="[{hora, ta, fc, spo2, etco2, temp}]",
            ),
        ),
        migrations.AlterField(
            model_name="triage",
            name="dolor_escala",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="0-10 EVA", null=True
            ),
        ),
        migrations.AlterField(
            model_name="triage",
            name="frecuencia_cardiaca",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="lpm", null=True
            ),
        ),
        migrations.AlterField(
            model_name="triage",
            name="frecuencia_resp",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="rpm", null=True
            ),
        ),
        migrations.AlterField(
            model_name="triage",
            name="glasgow",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="3-15", null=True
            ),
        ),
        migrations.AlterField(
            model_name="triage",
            name="hora_atencion",
            field=models.DateTimeField(
                blank=True, help_text="Hora en que inició la atención médica", null=True
            ),
        ),
        migrations.AlterField(
            model_name="triage",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="triage",
            name="motivo_consulta",
            field=models.TextField(
                help_text="Motivo de consulta en palabras del paciente"
            ),
        ),
        migrations.AlterField(
            model_name="triage",
            name="spo2",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="% saturación O2", null=True
            ),
        ),
        migrations.AlterField(
            model_name="triage",
            name="temperatura",
            field=models.DecimalField(
                blank=True, decimal_places=1, help_text="°C", max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="triage",
            name="tension_arterial",
            field=models.CharField(blank=True, help_text="ej: 120/80", max_length=15),
        ),
    ]
