# Generated by Django 5.0.6 on 2026-06-10 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("historia", "0009_firma_digital"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consentimientoinformado",
            name="firma_acompanante_imagen",
        ),
        migrations.RemoveField(
            model_name="consentimientoinformado",
            name="firma_imagen",
        ),
    ]
