# Generated by Django 5.0.6 on 2026-07-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("historia", "0013_egreso_indicaciones_alta"),
    ]

    operations = [
        migrations.AddField(
            model_name="liquidacioncirugia",
            name="ajuste_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="% de ajuste sobre la base tarifaria (ej: SOAT = ISS 2001 + 30%)",
                max_digits=6,
            ),
        ),
    ]
