# Generated by Django 5.0.6 on 2026-07-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("historia", "0014_liquidacioncirugia_ajuste_pct"),
    ]

    operations = [
        migrations.AddField(
            model_name="liquidacioncirugia",
            name="valor_smdlv",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Valor del SMDLV del año de atención (SOAT). 0 = no configurado",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="procedimientoliquidacion",
            name="grupo_soat",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Grupo quirúrgico del manual SOAT (Decreto 2423/96)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="liquidacioncirugia",
            name="ajuste_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="% de ajuste contractual sobre la base tarifaria",
                max_digits=6,
            ),
        ),
        migrations.AlterField(
            model_name="procedimientoliquidacion",
            name="orden",
            field=models.PositiveSmallIntegerField(
                help_text="1=mayor UVR/grupo, 2, 3..."
            ),
        ),
    ]
