# Generated by Django 5.0.6 on 2026-07-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("historia", "0015_liquidacioncirugia_valor_smdlv_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="descripcionquirurgica",
            name="cups_secundarios",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Procedimientos adicionales (máx. 2) realizados en el mismo acto",
            ),
        ),
        migrations.AddField(
            model_name="programacioncx",
            name="cups_secundarios",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Procedimientos adicionales (máx. 2) del mismo acto quirúrgico",
            ),
        ),
    ]
