# Generated by Django 5.0.6 on 2026-06-06 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rrhh", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liquidacionnomina",
            name="contrato",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="rrhh.contratoempleado",
            ),
        ),
    ]
