# Generated by Django 5.0.6 on 2026-06-06 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("epidemiologia", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notificacionsivigila",
            new_name="epidemiolog_evento_1375b2_idx",
            old_name="epidemiolog_evento_estado_idx",
        ),
        migrations.RenameIndex(
            model_name="notificacionsivigila",
            new_name="epidemiolog_semana__5f0390_idx",
            old_name="epidemiolog_semana_idx",
        ),
    ]
