# Generated by Django 5.0.6 on 2026-06-05 01:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("citas", "0001_initial"),
        ("pacientes", "0001_initial"),
        ("tarifas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fecha_atencion", models.DateTimeField()),
                (
                    "cups_principal",
                    models.CharField(
                        help_text="Código CUPS de la consulta", max_length=10
                    ),
                ),
                ("descripcion_cups", models.CharField(blank=True, max_length=300)),
                (
                    "diagnostico_principal",
                    models.CharField(help_text="CIE-10", max_length=10),
                ),
                (
                    "diagnostico_relacionado_1",
                    models.CharField(blank=True, max_length=10),
                ),
                (
                    "diagnostico_relacionado_2",
                    models.CharField(blank=True, max_length=10),
                ),
                (
                    "diagnostico_relacionado_3",
                    models.CharField(blank=True, max_length=10),
                ),
                (
                    "tipo_diagnostico",
                    models.CharField(
                        choices=[
                            ("1", "Impresión diagnóstica"),
                            ("2", "Confirmado nuevo"),
                            ("3", "Confirmado repetido"),
                        ],
                        default="1",
                        max_length=1,
                    ),
                ),
                ("motivo_consulta", models.TextField(blank=True)),
                ("enfermedad_actual", models.TextField(blank=True)),
                ("examen_fisico", models.TextField(blank=True)),
                ("plan_tratamiento", models.TextField(blank=True)),
                ("observaciones", models.TextField(blank=True)),
                ("numero_autorizacion", models.CharField(blank=True, max_length=50)),
                (
                    "modalidad",
                    models.CharField(
                        default="01",
                        help_text="Modalidad grupo servicio (RIPS)",
                        max_length=3,
                    ),
                ),
                (
                    "grupo_servicio",
                    models.CharField(
                        default="01",
                        help_text="Grupo de servicios (RIPS)",
                        max_length=3,
                    ),
                ),
                ("codigo_servicio", models.CharField(default="1", max_length=5)),
                (
                    "finalidad",
                    models.CharField(
                        default="13",
                        help_text="Finalidad tecnología en salud",
                        max_length=3,
                    ),
                ),
                (
                    "causa_atencion",
                    models.CharField(
                        default="26", help_text="Causa motivo atención", max_length=3
                    ),
                ),
                (
                    "valor_consulta",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "valor_copago",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Valor copago o cuota moderadora a cargo del paciente",
                        max_digits=14,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("abierta", "Abierta"),
                            ("cerrada", "Cerrada"),
                            ("facturada", "Facturada"),
                            ("anulada", "Anulada"),
                        ],
                        default="abierta",
                        max_length=15,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "cita",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consulta",
                        to="citas.cita",
                    ),
                ),
                (
                    "convenio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tarifas.convenioeps",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consultas",
                        to="citas.medico",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consultas",
                        to="pacientes.paciente",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_atencion"],
            },
        ),
        migrations.CreateModel(
            name="Medicamento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "cum",
                    models.CharField(
                        blank=True,
                        help_text="Código Único de Medicamento",
                        max_length=20,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("1", "Medicamento"), ("2", "Dispositivo médico")],
                        default="1",
                        max_length=1,
                    ),
                ),
                ("concentracion", models.CharField(blank=True, max_length=50)),
                ("unidad_medida", models.CharField(blank=True, max_length=20)),
                ("forma_farmaceutica", models.CharField(blank=True, max_length=50)),
                ("unidades", models.PositiveIntegerField(default=1)),
                (
                    "valor_unitario",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("fecha", models.DateTimeField()),
                (
                    "consulta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicamentos",
                        to="consultas.consulta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Procedimiento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cups", models.CharField(help_text="Código CUPS", max_length=10)),
                ("descripcion", models.CharField(max_length=300)),
                (
                    "valor_facturar",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "ambito",
                    models.CharField(
                        default="1",
                        help_text="1=Ambulatorio, 2=Hospitalario, 3=Urgencias",
                        max_length=2,
                    ),
                ),
                ("finalidad", models.CharField(default="01", max_length=3)),
                (
                    "personal_atiende",
                    models.CharField(
                        default="01",
                        help_text="01=Médico especialista, 02=Médico general...",
                        max_length=3,
                    ),
                ),
                ("via_diagnostica", models.CharField(default="1", max_length=2)),
                ("grupo", models.CharField(default="1", max_length=2)),
                ("cantidad", models.PositiveIntegerField(default=1)),
                ("orden", models.PositiveIntegerField(default=1)),
                (
                    "consulta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedimientos",
                        to="consultas.consulta",
                    ),
                ),
            ],
            options={
                "ordering": ["orden"],
            },
        ),
        migrations.AddIndex(
            model_name="consulta",
            index=models.Index(
                fields=["paciente", "fecha_atencion"],
                name="consultas_c_pacient_059bb7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consulta",
            index=models.Index(
                fields=["medico", "fecha_atencion"],
                name="consultas_c_medico__de156b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consulta",
            index=models.Index(fields=["estado"], name="consultas_c_estado_81d2fe_idx"),
        ),
    ]
