# Generated by Django 5.0.6 on 2026-06-05 01:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("consultas", "0001_initial"),
        ("tarifas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "numero_factus",
                    models.CharField(
                        blank=True, help_text="Ej: SETP990000001", max_length=50
                    ),
                ),
                (
                    "cufe",
                    models.CharField(
                        blank=True, help_text="Código Único FEV", max_length=100
                    ),
                ),
                ("qr_url", models.URLField(blank=True)),
                ("pdf_base64", models.TextField(blank=True)),
                ("rango_numeracion_id", models.IntegerField(blank=True, null=True)),
                (
                    "rips_json",
                    models.JSONField(
                        blank=True, help_text="RIPS generado Res. 948/2026", null=True
                    ),
                ),
                (
                    "cuv",
                    models.CharField(
                        blank=True,
                        help_text="Código Único de Validación MUV",
                        max_length=100,
                    ),
                ),
                ("rips_enviado_muv", models.BooleanField(default=False)),
                (
                    "xml_base64",
                    models.TextField(
                        blank=True, help_text="XML enviado a la DIAN en base64"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "descuento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "iva",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "valor_copago",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("enviada", "Enviada a Factus"),
                            ("validada", "Validada por DIAN"),
                            ("error", "Error de validación"),
                            ("anulada", "Anulada (nota crédito)"),
                        ],
                        default="borrador",
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("errores_dian", models.JSONField(blank=True, default=list)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("fecha_validacion", models.DateTimeField(blank=True, null=True)),
                (
                    "consulta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="factura",
                        to="consultas.consulta",
                    ),
                ),
                (
                    "convenio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tarifas.convenioeps",
                    ),
                ),
            ],
            options={
                "ordering": ["-creado_en"],
                "indexes": [
                    models.Index(
                        fields=["estado"], name="facturacion_estado_b4dd64_idx"
                    ),
                    models.Index(
                        fields=["numero_factus"], name="facturacion_numero__30a2d0_idx"
                    ),
                    models.Index(fields=["cufe"], name="facturacion_cufe_3cbe09_idx"),
                ],
            },
        ),
    ]
