# Generated by Django 5.0.6 on 2026-06-06 15:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0003_factura_historia_consulta_nullable"),
        ("historia", "0005_salud_notas_cx_ayudas"),
        ("pacientes", "0003_aseguradora_tarifario"),
        ("tarifas", "0003_tarifamedicamento"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prefactura",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("numero_prefactura", models.PositiveIntegerField(editable=False)),
                (
                    "fecha_inicio",
                    models.DateField(help_text="Inicio del período de atención"),
                ),
                (
                    "fecha_fin",
                    models.DateField(help_text="Fin del período / fecha de egreso"),
                ),
                (
                    "subtotal_eps",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total a cargo de la EPS/convenio",
                        max_digits=14,
                    ),
                ),
                (
                    "subtotal_paciente",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Copago / cuota moderadora a cargo del paciente",
                        max_digits=14,
                    ),
                ),
                (
                    "subtotal_no_facturable",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Valor de ítems excluidos o no facturables",
                        max_digits=14,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador — en construcción"),
                            ("en_revision", "En revisión por auditor"),
                            ("aprobada", "Aprobada — lista para facturar"),
                            ("facturada", "Facturada — FEV emitida"),
                            ("anulada", "Anulada"),
                        ],
                        default="borrador",
                        max_length=15,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "convenio",
                    models.ForeignKey(
                        blank=True,
                        help_text="EPS / convenio al que se factura",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tarifas.convenioeps",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prefacturas_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "factura",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prefactura",
                        to="facturacion.factura",
                    ),
                ),
                (
                    "historia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prefacturas",
                        to="historia.historiaclinica",
                    ),
                ),
                (
                    "ingreso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prefacturas",
                        to="historia.ingreso",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prefacturas",
                        to="pacientes.paciente",
                    ),
                ),
                (
                    "revisado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prefacturas_revisadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Prefactura",
                "verbose_name_plural": "Prefacturas",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="ItemPrefactura",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("consulta", "Consulta / Evolución"),
                            ("hospitalizacion", "Día de hospitalización"),
                            ("procedimiento", "Procedimiento quirúrgico / diagnóstico"),
                            ("anestesia", "Anestesia"),
                            ("medicamento", "Medicamento"),
                            (
                                "insumo_facturable",
                                "Insumo facturable (implante, osteosíntesis, contraste)",
                            ),
                            ("insumo_no_incluidoUVR", "Insumo no incluido en UVR"),
                            ("ayuda_diagnostica", "Ayuda diagnóstica"),
                            ("derechos_sala", "Derechos de sala quirúrgica"),
                            ("hoteleria", "Hotelería / Habitación"),
                            ("otro", "Otro"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        help_text="Nombre del servicio o insumo", max_length=400
                    ),
                ),
                (
                    "cups",
                    models.CharField(
                        blank=True, help_text="CUPS si aplica", max_length=10
                    ),
                ),
                (
                    "cum",
                    models.CharField(
                        blank=True, help_text="CUM si es medicamento", max_length=20
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(decimal_places=3, default=1, max_digits=10),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "descuento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "valor_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "destino",
                    models.CharField(
                        choices=[
                            ("eps", "A cobrar a EPS/convenio"),
                            ("paciente", "A cobrar al paciente (copago/cuota)"),
                            ("no_facturable", "No facturable / excluir"),
                        ],
                        default="eps",
                        max_length=15,
                    ),
                ),
                (
                    "motivo_exclusion",
                    models.CharField(
                        blank=True,
                        help_text="Por qué no es facturable (incluido en UVR, sin soporte, etc.)",
                        max_length=300,
                    ),
                ),
                (
                    "origen_tipo",
                    models.CharField(
                        blank=True,
                        help_text="Ej: OrdenHC, MedicamentoHC, AyudaDiagnostica, ProgramacionCx",
                        max_length=30,
                    ),
                ),
                (
                    "origen_id",
                    models.CharField(
                        blank=True, help_text="UUID del objeto origen", max_length=40
                    ),
                ),
                (
                    "es_manual",
                    models.BooleanField(
                        default=False,
                        help_text="True si el facturador lo agregó manualmente",
                    ),
                ),
                ("cie10", models.CharField(blank=True, max_length=10)),
                ("fecha_servicio", models.DateField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "prefactura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="facturacion.prefactura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de prefactura",
                "verbose_name_plural": "Ítems de prefactura",
                "ordering": ["tipo", "creado_en"],
            },
        ),
        migrations.AddIndex(
            model_name="prefactura",
            index=models.Index(
                fields=["numero_prefactura"], name="facturacion_numero__3778c4_idx"
            ),
        ),
    ]
