# Generated by Django 5.0.6 on 2026-06-06 16:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0004_prefactura_items"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotaAjusteRIPS",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cuv_original",
                    models.CharField(
                        blank=True,
                        help_text="CUV del RIPS original (obtenido de Factus)",
                        max_length=120,
                    ),
                ),
                (
                    "numero_factus_original",
                    models.CharField(
                        blank=True,
                        help_text="Número de factura original en Factus",
                        max_length=50,
                    ),
                ),
                (
                    "motivo_tipo",
                    models.CharField(
                        choices=[
                            ("diagnostico", "Diagnóstico incorrecto (CIE-10)"),
                            ("cups", "Código de procedimiento incorrecto (CUPS)"),
                            ("datos_paciente", "Datos demográficos del paciente"),
                            ("fecha_servicio", "Fecha de servicio incorrecta"),
                            ("tipo_usuario", "Tipo de usuario / régimen incorrecto"),
                            ("via_ingreso", "Vía de ingreso incorrecta"),
                            ("causa_externa", "Causa externa incorrecta"),
                            ("finalidad", "Finalidad de la consulta incorrecta"),
                            ("otro", "Otro error clínico"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "motivo_detalle",
                    models.TextField(
                        help_text="Descripción del error encontrado y la corrección aplicada"
                    ),
                ),
                (
                    "datos_originales",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot de los valores incorrectos",
                    ),
                ),
                (
                    "datos_corregidos",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot de los valores corregidos",
                    ),
                ),
                (
                    "rips_ajuste_json",
                    models.JSONField(
                        blank=True,
                        help_text="RIPS JSON con datos clínicos corregidos",
                        null=True,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("enviada", "Enviada a MinSalud"),
                            ("aceptada", "Aceptada"),
                            ("rechazada", "Rechazada"),
                        ],
                        default="borrador",
                        max_length=20,
                    ),
                ),
                (
                    "cuv_ajuste",
                    models.CharField(
                        blank=True,
                        help_text="CUV asignado al RIPS de ajuste por MinSalud",
                        max_length=120,
                    ),
                ),
                (
                    "respuesta_factus",
                    models.JSONField(
                        blank=True,
                        help_text="Respuesta completa de la API Factus",
                        null=True,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notas_ajuste_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "factura",
                    models.ForeignKey(
                        help_text="Factura cuyo RIPS se está ajustando",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas_ajuste",
                        to="facturacion.factura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota de ajuste RIPS",
                "verbose_name_plural": "Notas de ajuste RIPS",
                "ordering": ["-creado_en"],
            },
        ),
    ]
