# Generated by Django 5.0.6 on 2026-06-06 16:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion", "0005_nota_ajuste_rips"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotaDocumento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("NC", "Nota crédito"), ("ND", "Nota débito")],
                        max_length=2,
                    ),
                ),
                (
                    "concepto",
                    models.CharField(
                        help_text="Código del concepto según tipo (NC: 1-5, ND: 1-4)",
                        max_length=2,
                    ),
                ),
                (
                    "descripcion_concepto",
                    models.TextField(
                        help_text="Descripción del motivo de la nota crédito/débito"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "valor_descuento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "numero_factus",
                    models.CharField(
                        blank=True,
                        help_text="Número asignado por Factus (ej: NC-001)",
                        max_length=50,
                    ),
                ),
                (
                    "cufe",
                    models.CharField(
                        blank=True,
                        help_text="CUFE de la nota (generado por DIAN)",
                        max_length=200,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("enviada", "Enviada a DIAN"),
                            ("validada", "Validada DIAN"),
                            ("rechazada", "Rechazada"),
                            ("anulada", "Anulada"),
                        ],
                        default="borrador",
                        max_length=20,
                    ),
                ),
                ("errores_dian", models.JSONField(blank=True, null=True)),
                ("respuesta_factus", models.JSONField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notas_documento_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "factura_referencia",
                    models.ForeignKey(
                        help_text="FEV original que se está ajustando",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notas_documento",
                        to="facturacion.factura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota crédito / débito",
                "verbose_name_plural": "Notas crédito / débito",
                "ordering": ["-creado_en"],
            },
        ),
    ]
