# Generated by Django 5.0.6 on 2026-06-05 01:35

import django.db.models.deletion
import django_tenants.postgresql_backend.base
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consultorio",
            fields=[
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre del consultorio o clínica", max_length=200
                    ),
                ),
                ("nit", models.CharField(max_length=20, unique=True)),
                (
                    "codigo_prestador",
                    models.CharField(
                        blank=True,
                        help_text="Código habilitación MinSalud",
                        max_length=20,
                    ),
                ),
                ("razon_social", models.CharField(blank=True, max_length=200)),
                ("direccion", models.CharField(blank=True, max_length=200)),
                (
                    "municipio_codigo",
                    models.CharField(
                        default="08001",
                        help_text="DANE — 08001=Barranquilla",
                        max_length=10,
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("basico", "Básico (1 médico, 100 facturas/mes)"),
                            ("pro", "Pro (5 médicos, ilimitado)"),
                            ("clinica", "Clínica (ilimitado + API)"),
                        ],
                        default="basico",
                        max_length=20,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_vencimiento", models.DateField(blank=True, null=True)),
                (
                    "factus_base_url",
                    models.CharField(
                        blank=True,
                        default="https://api-sandbox.factus.com.co",
                        help_text="URL Factus (sandbox o producción) del consultorio",
                        max_length=200,
                    ),
                ),
                ("factus_client_id", models.CharField(blank=True, max_length=200)),
                ("factus_client_secret", models.CharField(blank=True, max_length=255)),
                (
                    "factus_username",
                    models.CharField(
                        blank=True,
                        help_text="Email/usuario Factus del consultorio",
                        max_length=150,
                    ),
                ),
                ("factus_password", models.CharField(blank=True, max_length=255)),
                (
                    "factus_rango_numeracion_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID del rango de numeración en Factus",
                        null=True,
                    ),
                ),
                (
                    "resolucion_dian",
                    models.CharField(
                        blank=True,
                        help_text="Número de la resolución DIAN de facturación",
                        max_length=50,
                    ),
                ),
                (
                    "resolucion_fecha",
                    models.DateField(
                        blank=True, help_text="Fecha de la resolución DIAN", null=True
                    ),
                ),
                (
                    "factura_prefijo",
                    models.CharField(
                        blank=True,
                        help_text="Prefijo de la factura (ej: SETP, FE)",
                        max_length=10,
                    ),
                ),
                (
                    "factura_rango_desde",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Número inicial autorizado en la resolución",
                        null=True,
                    ),
                ),
                (
                    "factura_rango_hasta",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Número final autorizado en la resolución",
                        null=True,
                    ),
                ),
                (
                    "factura_leyenda",
                    models.TextField(
                        blank=True,
                        help_text="Leyenda/texto legal que aparece en la representación gráfica (PDF)",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Consultorio",
                "verbose_name_plural": "Consultorios",
            },
        ),
        migrations.CreateModel(
            name="Dominio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="tenants.consultorio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dominio",
                "verbose_name_plural": "Dominios",
            },
        ),
    ]
