# Generated by Django 5.0.6 on 2026-06-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultorio",
            name="departamento",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="consultorio",
            name="firma_factura_cargo",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="consultorio",
            name="firma_factura_nombre",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="consultorio",
            name="logo_url",
            field=models.TextField(
                blank=True, help_text="URL o base64 del logo de la IPS"
            ),
        ),
        migrations.AddField(
            model_name="consultorio",
            name="nivel_atencion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Nivel I"),
                    ("2", "Nivel II"),
                    ("3", "Nivel III"),
                    ("4", "Nivel IV"),
                ],
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="consultorio",
            name="regimen",
            field=models.CharField(
                blank=True,
                choices=[
                    ("contributivo", "Contributivo"),
                    ("subsidiado", "Subsidiado"),
                    ("mixto", "Mixto"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="consultorio",
            name="regimen_tributario",
            field=models.CharField(
                blank=True,
                choices=[
                    ("simplificado", "Régimen Simplificado"),
                    ("comun", "Régimen Común"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="consultorio",
            name="representante_legal",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="consultorio",
            name="sitio_web",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
