# Generated by Django 5.0.6 on 2026-06-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_add_ips_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultorio",
            name="regimen",
            field=models.CharField(
                blank=True,
                choices=[
                    ("contributivo", "Contributivo"),
                    ("subsidiado", "Subsidiado"),
                    ("mixto", "Mixto (Contributivo y Subsidiado)"),
                    (
                        "especial",
                        "Especial y de excepción (FF.MM., Policía, Magisterio, Ecopetrol)",
                    ),
                    ("no_aplica", "No aplica (servicios particulares)"),
                ],
                help_text="Régimen de salud de los afiliados que atiende (REPS/MinSalud)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="consultorio",
            name="regimen_tributario",
            field=models.CharField(
                blank=True,
                choices=[
                    ("simple", "Régimen Simple de Tributación (SIMPLE)"),
                    ("ordinario", "Régimen Ordinario del Impuesto sobre la Renta"),
                    (
                        "no_responsable_iva",
                        "No Responsable de IVA (antes Simplificado)",
                    ),
                    ("responsable_iva", "Responsable de IVA (antes Régimen Común)"),
                    ("gran_contribuyente", "Gran Contribuyente"),
                    ("entidad_publica", "Entidad Pública"),
                ],
                help_text="Régimen tributario ante la DIAN",
                max_length=30,
            ),
        ),
    ]
