# Generated by Django 5.0.6 on 2026-06-05 01:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pacientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConvenioEPS",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "numero_contrato",
                    models.CharField(
                        help_text="Número del contrato con la EPS", max_length=100
                    ),
                ),
                ("vigencia_desde", models.DateField()),
                ("vigencia_hasta", models.DateField()),
                (
                    "cucon",
                    models.CharField(
                        help_text="Código Único de Contrato SHA-256 (Res. 948/2026). Obligatorio en FEV.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "tipo_tarifa",
                    models.CharField(
                        choices=[
                            ("SOAT", "SOAT"),
                            ("ISS_2001", "ISS 2001"),
                            ("ISS_2004", "ISS 2004"),
                            ("PARTICULAR", "Particular"),
                            ("CONVENIO", "Convenio EPS"),
                            ("MANUAL", "Manual interno"),
                        ],
                        default="CONVENIO",
                        max_length=20,
                    ),
                ),
                (
                    "porcentaje_copago",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="% copago a cargo del paciente",
                        max_digits=5,
                    ),
                ),
                (
                    "valor_cuota_moderadora",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("activo", models.BooleanField(default=True)),
                ("observaciones", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "aseguradora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="convenios",
                        to="pacientes.aseguradora",
                    ),
                ),
            ],
            options={
                "verbose_name": "Convenio EPS",
                "verbose_name_plural": "Convenios EPS",
                "ordering": ["-vigencia_desde"],
            },
        ),
        migrations.CreateModel(
            name="TarifaProcedimiento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo_tarifa",
                    models.CharField(
                        choices=[
                            ("SOAT", "SOAT"),
                            ("ISS_2001", "ISS 2001"),
                            ("ISS_2004", "ISS 2004"),
                            ("PARTICULAR", "Particular"),
                            ("CONVENIO", "Convenio EPS"),
                            ("MANUAL", "Manual interno"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cups",
                    models.CharField(
                        help_text="Código CUPS del procedimiento", max_length=10
                    ),
                ),
                ("descripcion", models.CharField(max_length=300)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=14)),
                ("vigente_desde", models.DateField()),
                ("vigente_hasta", models.DateField(blank=True, null=True)),
                (
                    "convenio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarifas",
                        to="tarifas.convenioeps",
                    ),
                ),
            ],
            options={
                "ordering": ["cups"],
                "unique_together": {("convenio", "cups", "vigente_desde")},
            },
        ),
    ]
