# Generated by Django 5.0.6 on 2026-06-05 03:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarifas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualTarifario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: SOAT 2026, ISS, Particular", max_length=200
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("SOAT", "SOAT"),
                            ("ISS_2001", "ISS 2001"),
                            ("ISS_2004", "ISS 2004"),
                            ("PARTICULAR", "Particular"),
                            ("CONVENIO", "Convenio EPS"),
                            ("MANUAL", "Manual interno"),
                        ],
                        default="MANUAL",
                        max_length=20,
                    ),
                ),
                (
                    "porcentaje_ajuste",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="% sobre valor base. 30 = +30%, -10 = -10%",
                        max_digits=6,
                    ),
                ),
                (
                    "es_predeterminado",
                    models.BooleanField(
                        default=False,
                        help_text="Tarifa usada cuando el paciente no tiene una asignada",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("vigente_desde", models.DateField(blank=True, null=True)),
                ("vigente_hasta", models.DateField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Manual tarifario",
                "verbose_name_plural": "Manuales tarifarios",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="ItemTarifario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cups", models.CharField(help_text="Código CUPS", max_length=10)),
                (
                    "descripcion",
                    models.CharField(
                        blank=True,
                        help_text="Descripción del procedimiento",
                        max_length=400,
                    ),
                ),
                (
                    "valor_base",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor base del manual",
                        max_digits=14,
                    ),
                ),
                (
                    "manual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="tarifas.manualtarifario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem tarifario",
                "verbose_name_plural": "Ítems tarifarios",
                "ordering": ["cups"],
                "unique_together": {("manual", "cups")},
            },
        ),
    ]
