# Generated by Django 5.0.6 on 2026-06-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarifas", "0003_tarifamedicamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemtarifario",
            name="cups_rips",
            field=models.CharField(
                blank=True,
                help_text="Código CUPS base para RIPS (sin sufijo). Auto-calculado.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="itemtarifario",
            name="es_paquete",
            field=models.BooleanField(
                default=False,
                help_text="True si este ítem es un paquete tarifario con sufijo",
            ),
        ),
        migrations.AlterField(
            model_name="itemtarifario",
            name="cups",
            field=models.CharField(
                help_text="Código CUPS (o código paquete, ej: 876122-1)", max_length=15
            ),
        ),
        migrations.AlterField(
            model_name="itemtarifario",
            name="descripcion",
            field=models.CharField(
                blank=True,
                help_text="Descripción del procedimiento o paquete",
                max_length=400,
            ),
        ),
    ]
