# Generated by Django 5.0.6 on 2026-07-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarifas", "0004_add_porcentaje_aseguradora_y_paquetes_tarifario"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemtarifario",
            name="uvr",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Puntos UVR del procedimiento (para liquidación de cirugías ISS/SOAT)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="itemtarifario",
            name="valor_base",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Valor base del manual (pesos)",
                max_digits=14,
            ),
        ),
    ]
