# Generated by Django 5.0.6 on 2026-07-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarifas", "0005_itemtarifario_uvr_alter_itemtarifario_valor_base"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrupoQuirurgicoSOAT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grupo",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (2, "Grupo 2"),
                            (3, "Grupo 3"),
                            (4, "Grupo 4"),
                            (5, "Grupo 5"),
                            (6, "Grupo 6"),
                            (7, "Grupo 7"),
                            (8, "Grupo 8"),
                            (9, "Grupo 9"),
                            (10, "Grupo 10"),
                            (11, "Grupo 11"),
                            (12, "Grupo 12"),
                            (13, "Grupo 13"),
                            (20, "Grupo 20"),
                            (21, "Grupo 21"),
                            (22, "Grupo 22"),
                            (23, "Grupo 23"),
                        ],
                        unique=True,
                    ),
                ),
                (
                    "smdlv_cirujano",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Honorarios cirujano en SMDLV",
                        max_digits=8,
                    ),
                ),
                (
                    "smdlv_anestesiologo",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Honorarios anestesiólogo en SMDLV",
                        max_digits=8,
                    ),
                ),
                (
                    "smdlv_ayudante",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Ayudantía quirúrgica en SMDLV (grupos ≤5 no liquidan ayudante)",
                        max_digits=8,
                    ),
                ),
                (
                    "smdlv_sala",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Derechos de sala en SMDLV",
                        max_digits=8,
                    ),
                ),
                (
                    "smdlv_materiales",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Materiales de sutura y curación en SMDLV",
                        max_digits=8,
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo quirúrgico SOAT",
                "verbose_name_plural": "Grupos quirúrgicos SOAT",
                "ordering": ["grupo"],
            },
        ),
    ]
